# Generated by Django 5.2.6 on 2025-09-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_report_report_type_alter_report_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
