# Generated by Django 5.2.6 on 2025-09-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_image_post_image_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
