# Generated by Django 5.2.6 on 2025-09-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_report_report_type_user_social'),
    ]

    operations = [
        # 'report_type' column already exists in the database; skip AddField to avoid DuplicateColumn
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
