# Generated by Django 5.2.6 on 2025-09-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_report_report_type_alter_comment_body_and_more'),
    ]

    operations = [
        # 'report_type' already present in DB; skip AddField to avoid DuplicateColumn
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
